### ISSUE TITLE
How to use the libary to load/parse Energie e-Factuur

### ISSUE THREAD

**Issue by fvandillen** [UblSharp/UblSharp#12]
I've been able to load the Energie e-Factuur as a regular UBL InvoiceType.

``var ubl = UblDocument.Load<InvoiceType>(xmlStream);``

However, I would like to use the classes available in the SEeF extension. How do I parse those as well? Is there a specific InvoiceType for the Energie e-Factuur?

**Comment by remcoros** [comment]
I haven't used any extension types myself yet, so I don't know off the top of my head.

The content of the SEeF xml types are inside the 'UblExtensions' property, but I'll have to check howto extract them from a regular InvoiceType.

Not checked/compiled, but probably something like this (I'll add a real sample/test to the tests project):

```cs
var serializer = new XmlSerializer<SEEFExtensionWrapperType>();
var invoice = UblDocument.Load<InvoiceType>(xmlStream);
var extElement = invoice.UblExtensions[0].ExtensionContent; // this is of type 'XmlElement'
var seef = (SEEFExtensionWrapperType)serializer.Deserialize(new StringReader(extElement.ToString())); 
// seef now contains SEEFExtensionWrapperType
```

**Comment by fvandillen** [comment]
Thank you for your reply. In the mean time, i've managed to get it working exactly the way you suggested. 

```
var ubl = UblDocument.Load<InvoiceType>(xmlStream);
var xmlSerializer = new XmlSerializer(typeof(SEEFExtensionWrapperType));

using (var sr = new StringReader(ubl.UBLExtensions[0].ExtensionContent.OuterXml))
{
        var seef = (SEEFExtensionWrapperType)xmlSerializer.Deserialize(sr);
        Console.WriteLine("Extension ran.");
}
```

**Comment by remcoros** [comment]
That's awesome.

I'll reopen the issue as a reminder I need to add some tests / examples for this. And maybe (extension) methods to make this easier.

**Comment by fvandillen** [comment]
Oh, in addition to adding some examples: in practice, all utility suppliers and grid owners in the Netherlands use SEeF version 1.0 instead of 2.0. I've forked the library locally so it deserializes it to 1.0. Find and replace did the trick.

**Comment by remcoros** [comment]
Released UblSharp.SEeF 1.1.1 which uses V1 of the schema.

Also added an XmlSerializerFactory which allows to specify a SEeFVersion enum to be able to get a XmlSerializer which rewrites the xmlns from v1 to v2.

Also added some unit test how to use this here: https://github.com/UblSharp/UblSharp/blob/master/src/UblSharp.Tests/SEeF/InvoiceExtensionTests.cs
