### ISSUE TITLE
UBLExtensions -> ExtensionContent

### ISSUE THREAD

**Issue by rmpt** [UblSharp/UblSharp#14]
I'm trying to set some custom UBLExtensions of type ExtensionContent, but can't get the desired result.
I want to build an UBLExtensions similar to:

> &lt;ext:UBLExtension>
>       &lt;cbc:ID>MY_ID</cbc:ID>
>       &lt;ext:ExtensionContent>
>           &lt;cbc:Value>MY_VALUE</cbc:Value>
>        &lt;/ext:ExtensionContent>
> &lt;/ext:UBLExtension>

But there's no ExtensionContentType class, so I can't create mt ExtensionContent element. I also tryied to create it from a new XmlDocument (since ExtensionContent is of type XmlElement) but didn't manage to get it. So I assume there's something wrong with ExtensionContentType.

**Comment by remcoros** [comment]
The content of 'ExtensionContent' is untyped (xsd:any), so that's why it's an XmlElement.

You can use the XmlElement to do manual parsing, or use XmlSerializer something like this:


```csharp
var ubl = UblDocument.Load<InvoiceType>(xmlStream);
var xmlSerializer = new XmlSerializer(typeof(YourOwnType));

using (var sr = new StringReader(ubl.UBLExtensions[0].ExtensionContent.OuterXml))
{
        var yourtype = (YourOwnType)xmlSerializer.Deserialize(sr);
}
```

**Comment by remcoros** [comment]
here's an example using SEeFExtensionWrapperType: https://github.com/UblSharp/UblSharp/blob/master/src/UblSharp.Tests/SEeF/InvoiceExtensionTests.cs

hope that helps. If not, feel free to post some source / sample and I'll look into it.

**Comment by rmpt** [comment]
My problem is that I don't have the document, I'm building the doc myself. So your example works for an already existent XML, in my case, I don't have it.
The final UBLExtension should look like this:

> <ext:UBLExtension>
>       <cbc:ID xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2">GRUPO_FATURACAO</cbc:ID>
>       <ext:ExtensionContent>
>         <cbc:Value xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2">SAUDE</cbc:Value>
>       </ext:ExtensionContent>
>     </ext:UBLExtension>

My attemp is something like this:

> private UBLExtensionType BuildExtensionTypeElement(string idValue, string extesionContentValue)
> 		{
> 			var doc = new XmlDocument();
> 			doc.LoadXml(string.Format(
> 				"<ext:UBLExtensions " +
> 						"xmlns:ext=\"urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2\" " +
> 						"xmlns:cbc=\"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2\">" +
> 						"<ext:ExtensionContent><cbc:Value>{0}</cbc:Value>" +
> 					"</ext:ExtensionContent>" +
> 				"</ext:UBLExtensions>", extesionContentValue));
> 				var extensionContentElement = doc.DocumentElement;
> 				// do something with it?
> 			
> 			return new UBLExtensionType()
> 			{
> 				ID = new IdentifierType()
> 				{
> 					Value = idValue
> 				},
> 				//ExtensionContent = extContent
> 			};
> 		}

Your help would be much appreciated.
Thanks

**Comment by fvandillen** [comment]
Trying to do something similar with SEeF, putting custom extension content inside my UBL invoice: https://i.imgur.com/LVxODyx.png

Any help would be appreciated

**Comment by remcoros** [comment]
The XmlSerializer of 'Invoice' doesn't know about any types outside of UblSharp. (be it SEeF or your own types).

So the same way you should read the extension (manually trough parsing XmlElement, or using a different XmlSerializer), you should serialize / convert the custom type to an XmlElement and provide that to ExtensionContent.

I'll try to create a sample of this asap.

**Comment by rmpt** [comment]
I've done a test where I can put the Value as my example, but the namesoace is not present in any of the following tags:
UBLExtensions
UBLExtension
ExtensionContent
Value

it should be:
<ext:UBLExtensions xmlns:ext="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2">
```
<ext:UBLExtension>
    <cbc:ID>GRUPO_FATURACAO</cbc:ID>
    <ext:ExtensionContent>
        <cbc:Value>SAUDE</cbc:Value>
    </ext:ExtensionContent>
    </ext:UBLExtension>
</ext:UBLExtensions>

```

but is:
```
<UBLExtensions >
    <UBLExtension>
        <cbc:ID>GRUPO_FATURACAO</cbc:ID>
        <ExtensionContent>
            <Value>SAUDE</cbc:Value>
        </ExtensionContent>
    </UBLExtension>
</UBLExtensions>
```

**Comment by remcoros** [comment]
@fvandillen Sample for SEeF: https://github.com/UblSharp/UblSharp/blob/master/src/UblSharp.Tests/SEeF/InvoiceExtensionTests.cs#L60

@rmpt Sample for a type from CommonBasicComponents: https://github.com/UblSharp/UblSharp/blob/master/src/UblSharp.Tests/UseCases/CustomExtensionTests.cs

There are way too many CBC types, and they are not needed for (de)serialization, because they are just CCT types (Cct*)). That's why they are not defined in UblSharp.

When you want to explicitly use a type van Cbc, you're going to have to declare it yourself.

I recommend though, when you want to use UBL extension types, you create a wrapper type for your extension (Look at SEeF xsd here https://github.com/UblSharp/UblSharp/blob/master/src/UblSharp.SEeF.Generator/V1/SEeF_UBLExtension_v1.0.1.xsd and https://github.com/UblSharp/UblSharp/blob/master/src/UblSharp.SEeF/SEeF_UBLExtension_v1.0.1.generated.cs) and use that as your main extension container type.

I'll create a follow-up issue to look into adding some helper/extension methods making it easier to work with extension types.

**Comment by rmpt** [comment]
Thanks, that works for me :) Keep the good work

**Comment by mathi931** [comment]
Hello @remcoros,
I have kind of similar problem. I successfully attached the extension to the UBL but I can not remove the namespace declarations from it. If I serialize without declare the namespaces, The extension's properties won't have the shortened namespaces.
It's like the extension can not see the declared namespaces from the Invoice, or can not reach it. Do you have any idea how I should solve this ?

This is how now looks like:
![image](https://user-images.githubusercontent.com/51709088/196171890-ad41c431-a241-40c6-8a92-890f5811f2d8.png)

My desired result:
![image](https://user-images.githubusercontent.com/51709088/196172056-1b3773ae-8c0a-4466-a7a4-d8d042a894cb.png)

Meanwhile I found the solution

Just get the root element with XmlDocument, attach the extension and simply remove the attributes from the extension like this:

```
var ublXmlSerializer = new XmlSerializer(typeof(InvoiceType));

var xdoc = new XmlDocument();
using (var writer = xdoc.CreateNavigator().AppendChild())
{
    ublXmlSerializer.Serialize(writer, invoiceUbl, invoiceUblNameSpaces);
}

XmlDocumentFragment xfrag = xdoc.CreateDocumentFragment();
xfrag.InnerXml = xmlElementExtension.OuterXml;

var rootElement = xdoc.DocumentElement;
rootElement.ChildNodes[0].ChildNodes[0].AppendChild(xfrag);
rootElement.ChildNodes[0].ChildNodes[0].ChildNodes[0].Attributes?.RemoveAll();
```

**Comment by Milecaokta** [comment]
Hello @mathi931. 
I am also working on a similar request. Could you share your code?

**Comment by mathi931** [comment]
Sure @Milecaokta,
But as I see there will be problem with the attach process. Because The extension is not part of the ubl what will be serialized at the end. So just have to find another way to attach them together and remove namespaces what are already declared in the root.



        public class Program
        {
            static void Main(string[] args)
            {

            var invoiceUbl = new InvoiceType { ID = "Invoice1", UBLExtensions = new List<UBLExtensionType> { new UBLExtensionType() } };

            var extension = new TestExtensionType
            {
                InvoicedPrepaymentAmount = new InvoicedPrepaymentAmmount
                {
                    ID = new IdentifierType { Value = "Value1" },
                    TaxTotal = new TaxTotalType { TaxAmount = { Value = 1 } }
                }
            };
            extension.InvoicedPrepaymentAmount.TaxTotal.TaxAmount.Value = 1;



            var doc = new XmlDocument();
            var extensionXmlSerializer = new XmlSerializer(typeof(TestExtensionType));

            var extensionNameSpaces = new XmlSerializerNamespaces();
            extensionNameSpaces.Add("cbc", "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2");
            extensionNameSpaces.Add("cac", "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2");
            extensionNameSpaces.Add("xsd", "http://www.w3.org/2001/XMLSchema");
            extensionNameSpaces.Add("sbt", "http://mfin.gov.rs/srbdt/srbdtext");

            using (var writer = doc.CreateNavigator().AppendChild())
            {
                extensionXmlSerializer.Serialize(writer, extension, extensionNameSpaces);
            }

            //here we got the serialized extension as an XmlElement what can be attached as an ubl extension content

            var xmlElementExtension = doc.DocumentElement;

            invoiceUbl.UBLExtensions[0].ExtensionContent = xmlElementExtension;

            var invoiceUblNameSpaces = new XmlSerializerNamespaces();
            invoiceUblNameSpaces.Add("sbc", "urn:oasis:names:specification:ubl:schema:xsd:SignatureBasicComponents-2");
            invoiceUblNameSpaces.Add("sig", "urn:oasis:names:specification:ubl:schema:xsd:CommonSignatureComponents-2");
            invoiceUblNameSpaces.Add("cec", "urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2");


            string xml;
            using (StringWriter sw = new StringWriter())
            {
                XmlSerializer serializer = new XmlSerializer(typeof(InvoiceType));
                serializer.Serialize(sw, invoiceUbl, invoiceUblNameSpaces);
                xml = sw.ToString();
            }

            Console.ReadLine();
        }

        //sbt
        [Serializable]
        [XmlType("TestExtension", Namespace = "http://mfin.gov.rs/srbdt/srbdtext")]
        [XmlRoot(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:Invoice-2")]
        public class TestExtensionType
        {
            [XmlElement(Namespace = "http://www.w3.org/2001/XMLSchema")]
            public InvoicedPrepaymentAmmount InvoicedPrepaymentAmount { get; set; }
        }
        //xsd
        [Serializable]
        public class InvoicedPrepaymentAmmount
        {
            [XmlElement(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
            public IdentifierType ID { get; set; }

            [XmlElement(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
            public TaxTotalType TaxTotal { get; set; }
        }
    }

Result:
```
<?xml version="1.0" encoding="utf-16"?>
<Invoice xmlns:cec="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2" xmlns:sig="urn:oasis:names:specification:ubl:schema:xsd:CommonSignatureComponents-2" xmlns:sbc="urn:oasis:names:specification:ubl:schema:xsd:SignatureBasicComponents-2" xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2" xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2" xmlns="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2">
  <cec:UBLExtensions>
    <cec:UBLExtension>
      <cec:ExtensionContent>
        <TestExtension xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2" xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2" xmlns="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2">
          <xsd:InvoicedPrepaymentAmount>
            <cbc:ID>Value1</cbc:ID>
            <cac:TaxTotal>
              <cbc:TaxAmount>1</cbc:TaxAmount>
            </cac:TaxTotal>
          </xsd:InvoicedPrepaymentAmount>
        </TestExtension>
      </cec:ExtensionContent>
    </cec:UBLExtension>
  </cec:UBLExtensions>
  <cbc:ID>Invoice1</cbc:ID>
</Invoice>
```
