### ISSUE TITLE
How to wrap around TextType with [CDATA] content

### ISSUE THREAD

**Issue by jorgelfons** [UblSharp/UblSharp#18]

**Comment by jorgelfons** [comment]
Solved.!!!

**Comment by SebasCharria** [comment]
How to do ? @jorgelfons

**Comment by SebasCharria** [comment]
I Solved with this: https://stackoverflow.com/questions/50368923/how-can-i-use-cdata-with-generated-c-sharp-classes-from-xsd-exe 
💯
