### ISSUE TITLE
Opening .sln with VS2019

### ISSUE THREAD

**Issue by fvandillen** [UblSharp/UblSharp#21]
When opening the solution with VS2019, errors occur on the following projects:
- UblSharp
- UblSharp.Generator.Core
- UblSharp.SEeF
- UblSharp.Tests
- UblSharp.Validation

The UblSharp.*.Generator projects load fine, but of course they are missing referenced projects and will not build.

The error reported in the console is as follows:
```
The project file cannot be opened by the project system, because it is missing some critical imports or the referenced SDK cannot be found.

Detailed Information:
Unable to locate the .NET Core SDK. Check that it is installed and that the version specified in global.json (if any) matches the installed version.
```

As per dotnet --list-sdks, these are all present: 

```
C:\Users\admin>dotnet --list-sdks
2.1.4 [C:\Program Files\dotnet\sdk]
2.1.104 [C:\Program Files\dotnet\sdk]
2.1.200 [C:\Program Files\dotnet\sdk]
2.1.202 [C:\Program Files\dotnet\sdk]
2.1.402 [C:\Program Files\dotnet\sdk]
2.1.500 [C:\Program Files\dotnet\sdk]
2.1.602 [C:\Program Files\dotnet\sdk]
2.1.604 [C:\Program Files\dotnet\sdk]
2.1.700 [C:\Program Files\dotnet\sdk]
2.1.801 [C:\Program Files\dotnet\sdk]
2.2.104 [C:\Program Files\dotnet\sdk]
2.2.105 [C:\Program Files\dotnet\sdk]
2.2.107 [C:\Program Files\dotnet\sdk]
2.2.108 [C:\Program Files\dotnet\sdk]
2.2.203 [C:\Program Files\dotnet\sdk]
2.2.204 [C:\Program Files\dotnet\sdk]
2.2.205 [C:\Program Files\dotnet\sdk]
2.2.300 [C:\Program Files\dotnet\sdk]
2.2.301 [C:\Program Files\dotnet\sdk]
2.2.401 [C:\Program Files\dotnet\sdk]
3.0.100-preview7-012821 [C:\Program Files\dotnet\sdk]
```

Any help would be appreciated, so I can add the SEeF 2.1 and 3.0 files to the project via PR.

**Comment by remcoros** [comment]
I think it's due to global.json being present in the root, requiring SDK 2.0.3

I'm not sure what is recommended (to check in this file or not), but you can work around it by deleting it, or updating the SDK version string to something you have on your machine.

**Comment by fvandillen** [comment]
Removing global.json did the trick.
