### ISSUE TITLE
.Net 4.6 Version

### ISSUE THREAD

**Issue by lmfmsilva** [UblSharp/UblSharp#3]
I need .Net 4.6 version of your code (I would like to use the UblSharp.dll in a Azure Function). I tried to change the framework of your 4.5 version to 4.6 but there are  some issues that I can't solve.

Can you help me?

Best regards

**Comment by remcoros** [comment]
You should be able to use the net45 version from a 4.6 application. What issues are you running into ?

**Comment by lmfmsilva** [comment]
I was tryig to use your classes in an Azure Function (first by adding the dll and then by adding you nuget via project.json) and was getting strange errors in the azure function (something related to httpresponse in the webhook that seemed to be overloaded by your classes).

After some trial and error I tried to include the ubllarsen nuget and solved my problem (I just want a simple API to generate 2.0 UBL invoices).

**Comment by remcoros** [comment]
It could be a serialization issue. I've not used the raw ubl documents in a web api, so I don't know how they behave there.

It would help if you have any error / exception logs.

**Comment by remcoros** [comment]
re-open this issue if it's still an issue. A lot has changed since netstandard 2.0.
