### ISSUE TITLE
Round Decimal Values to Two Digits

### ISSUE THREAD

**Issue by mah-dc** [UblSharp/UblSharp#38]
Hello,

I'm using `InvoiceType.ToXDocument().ToString()` to generate XML for an Invoice object, How to round all decimal values to two digits in the output XML string ?

For example:
Change `<cbc:TaxAmount currencyID="SAR">0.60000</cbc:TaxAmount>` to `<cbc:TaxAmount currencyID="SAR">0.60</cbc:TaxAmount>`

Thanks

**Comment by remcoros** [comment]
This is the default behavior of the .NET XmlSerializer, see: https://stackoverflow.com/questions/10330155/c-sharp-xml-serialization-and-decimal-value

There is literally no difference between 0.6 / 0.60 / 0.6000 when you do proper serialization/deserialization, except for how it 'looks' in xml. So I'm not sure if (and why) this would be an issue.

If really needed, you would have to use the .NET XmlSerializer customization features to override the default behavior. e.g. like described here: https://stackoverflow.com/questions/10330155/c-sharp-xml-serialization-and-decimal-value

**Comment by mah-dc** [comment]
> This is the default behavior of the .NET XmlSerializer, see: https://stackoverflow.com/questions/10330155/c-sharp-xml-serialization-and-decimal-value
> 
> There is literally no difference between 0.6 / 0.60 / 0.6000 when you do proper serialization/deserialization, except for how it 'looks' in xml. So I'm not sure if (and why) this would be an issue.
> 
> If really needed, you would have to use the .NET XmlSerializer customization features to override the default behavior. e.g. like described here: https://stackoverflow.com/questions/10330155/c-sharp-xml-serialization-and-decimal-value

Thanks for the reply,

The generated XML is validated by a Tax Authority that restrict the decimal numbers to two, so I need the output like that.

How to tell UblSharp to use my custom XmlSerializer ?

**Comment by remcoros** [comment]
> The generated XML is validated by a Tax Authority that restrict the decimal numbers to two, so I need the output like that.

yeah, that's pretty annoying. UblSharp / UBL doesn't know anything about the additional validation rules schemas of national authorities like PEPPOL.

From what I remember when I was researching this, it uses schematron (XSLT), but the .NET support of xslt/schematron is pretty bad. This is the main reason UblSharp stuck with pure UBL specification and relies on the default behavior of .NET xml serialization.

For more control / advanced processing of XML in .NET I would advise a library like Saxon, where the support of XML/XSLT 2 is way more advanced and customizable than in .NET. This requires more manual xml manipulation though.

I don't know if (and how) it would be possible to "hack" this into UblSharp from the outside. You might be able to override the TaxAmount class and implement IXmlSerializable to write custom xml. Then, replace all 'Tax' properties from the main document and lines with your own instance of the TaxAmount. I'm not sure this would be possible, but this might be worth a try.

Final option (using UblSharp) would be to make the customizations inside UblSharp itself and compile your own version.
